# Generated by Django 3.2.8 on 2021-10-14 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagramapp', '0002_auto_20211014_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagramapp.image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagramapp.profile')),
            ],
        ),
    ]
